### ISSUE TITLE
#include<math.h>not working

### ISSUE THREAD

**Issue by disguiser77** [TOSUN-Shanghai/TSMaster#108]
![微信图片_20230713113524](https://github.com/TOSUN-Shanghai/TSMaster/assets/54281706/dae26437-085a-4511-9401-624009f0328d)
I want to use the functions `fmaxf` and `fabsf` from `math.h`, but the compiler gives an error: `"error: use of undeclared identifier 'fmaxf'"`. Why is this happening and how can I resolve it?

**Comment by freshhope** [comment]
this is because TSMaster's default compiler is C++ builder, you must use the following include:
#include <algorithm>

and then use the following code:

std::max(1.1,2.2);

this will solve your problem.
