### ISSUE TITLE
【CAN节点仿真】数据库中的信号只有部分在随机变化

### ISSUE THREAD

**Issue by EngrIMBA** [TOSUN-Shanghai/TSMaster#113]
使用CAN总线仿真并启动仿真之后，只有部分信号会随机变化，请问有没有办法可以让所有的信号都随机变化呢？
![image](https://github.com/TOSUN-Shanghai/TSMaster/assets/105102093/b7650cc4-ca10-487d-8408-70384b8c400c)

**Comment by freshhope** [comment]
你所谓的随机变化指的是这些信号拥有初始值，你要让其他信号也拥有初始值是不合理的，因为不是所有信号初始值都是非0

**Comment by EngrIMBA** [comment]
@freshhope 就是像“报文发送”界面中每个信号有对应的信号随机生成器一样，我发现开始模拟这些节点的时候，只有少部分的信号再随机变化，大部分的信号如你所说只是给了初始值，并没有随机变化。

**Comment by freshhope** [comment]
要实现对rbs的信号控制，请使用图形程序或小程序api设置值，如果不用程序，可使用信号映射配合信号激励中的生成器来实现随机变化。

自动变化每一个信号可以使用小程序api遍历数据库来实现。
