### ISSUE TITLE
利用VN1640A操作基础诊断复合诊断服务无法正常发出

### ISSUE THREAD

**Issue by shanjiaomou** [TOSUN-Shanghai/TSMaster#124]
![image](https://github.com/TOSUN-Shanghai/TSMaster/assets/85399244/9fc3c655-d9d1-4bfb-9a9a-ccd97f77ed7e)

**Comment by TSSkyhits** [comment]
复合诊断传输层位于硬件设备中，要使用此功能，需要采用TOSUN自家的硬件设备。
