### ISSUE TITLE
CAN Database file path

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#14]
**Feature Request:** On the ‘CAN Database’ window, currently if DBCs are added, they are copied to C:\Program Files (x86)\TOSUN\TSMAster\bin\Configuration\TOSUN\DB\CAN\ etc, and if edited from within TSmaster it edits that local copy.
- It would be good to be able to specify the file copy path, so that it could stay with the configuration file folder and make sharing easier
- It could also be good to have a ‘Add DBC without copy’ button, that adds the DBC but doesn’t make a local copy. This would allow the DBC to be edited by another program and would update without having to remove/re-add the DBC

**Comment by freshhope** [comment]
the latest version now supports linking external dbc file by unchecking this option:

![image](https://user-images.githubusercontent.com/16358754/158480604-51de35d5-6388-474c-89ce-da618adef412.png)

when you click edit button in the database viewer, CAN db++ will be opened and you can edit the source dbc in the editor, by closing this editor, the database will be automatically refreshed.
