### ISSUE TITLE
'CAN statistics' page updates

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#15]
**Feature Request:** On the ‘CAN Statistics’ window, show the specified baud rate of each channel
**Feature Request:** Have 'Clear Statistics' button, to reset error frame count
![image](https://user-images.githubusercontent.com/27743747/140978238-6ebbf2ab-33be-4299-b84f-d0a479d4946c.png)

**Comment by freshhope** [comment]
[1]
![image](https://user-images.githubusercontent.com/16358754/141705426-1af603a0-db55-4caf-9ccd-17d51dc66c2c.png)

[2] you can right click to clear currently, I will add toolbar icon in next release
