### ISSUE TITLE
CAN Database window resizing

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#16]
**Feature request:** On the ‘CAN Database’ window, be able to resize the Channel Assignment window:

![image](https://user-images.githubusercontent.com/27743747/140978398-fc9f0058-acb3-4e20-9003-6e4d8a19c85e.png)

**Comment by freshhope** [comment]
please upg. 
![image](https://user-images.githubusercontent.com/16358754/141705479-f668d7fa-25e4-40b3-8626-b274b94e3587.png)
