### ISSUE TITLE
Adding signals to graphics/numeric display from trace

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#18]
**Feature request:** If multiple signals are selected within the trace, going 'Monitor signals in... -> Graphics/Numeric Display', it would make sense to add all the selected signals to the Numeric Display

![image](https://user-images.githubusercontent.com/27743747/141231789-90d5c49a-d3ef-404e-a56c-e37e7bed63bc.png)

**Comment by freshhope** [comment]
solved, update to latest beta version within software
