### ISSUE TITLE
Graphics varible selection

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#19]
**Bug:** If the order of variables on the 'graphics' window changes, double-clicking a variable to change the settings will open the wrong variable.

Example: order was changed on the below variables, I double-clicked on 'Direction_Command' and it opens 'D2_Motor_Speed' settings

![image](https://user-images.githubusercontent.com/27743747/141841385-fd3c720f-4887-4a31-ba62-263207d2f552.png)

**Comment by freshhope** [comment]
upg. to beta version will resolve this problem
