### ISSUE TITLE
WinUSB WCID support

### ISSUE THREAD

**Issue by kubsztal** [TOSUN-Shanghai/TSMaster#2]
Would be rally great if besides supported commercial CAN vendors you could support WinUSB WCID protocol, which is used by several open source CAN projects, e.g.:
https://github.com/candle-usb/candleLight_fw
https://canable.io/
https://github.com/HubertD/cangaroo

**Comment by freshhope** [comment]
Thank you very much for the suggestion! please wait until this feature is out.

**Comment by freshhope** [comment]
Please see release on 2021-10-06

![image](https://user-images.githubusercontent.com/16358754/136236905-6e3cf25b-503d-448a-976b-2bd6c3f13a93.png)

![image](https://user-images.githubusercontent.com/16358754/136237177-ebd2f33b-6bc5-4af4-b22e-6fd9efb583a3.png)


Rx Benchmark under 500 Kbps:
CH1: CANable
CH2: TC1005
TC1005 tx around 10250 frames per second (100% bus load utilized, TC1005 performance > 100000 frames per second in all its 5 CAN channels)
CANable rx around 10250 frames per second (single rx performance is OK)
![image](https://user-images.githubusercontent.com/16358754/136235114-fae52c4d-98d9-42c7-b280-a636270e2657.png)


Tx Benchmark under 500 Kbps:
CANable tx around 2700 frames per second (max tx frame rate should be 10250)
![image](https://user-images.githubusercontent.com/16358754/136235245-e80539a7-9713-4223-850a-1e72d4561cda.png)

**Comment by parthmpatel1110** [comment]
Hi, 

Can you update code to support 
https://netcult.ch/elmue/CANable%20Firmware%20Update/. Fw ?
