### ISSUE TITLE
How to use these two API functions in the mini program？

### ISSUE THREAD

**Issue by XieYY135** [TOSUN-Shanghai/TSMaster#23]
double d = com.get_can_signal_value(TSgn1, &c.FData[0]);
    com.set_can_signal_value(TSgn1, &c.FData[0], 12.3);
    The two apis have a key parameter: the definition of the signal attribute (such as TSgn1).  But the variables used to describe signal properties can't be found directly in the default header file or in the database header file  of the mini program.

**Comment by freshhope** [comment]
com.set_can_signal_value and com.get_can_signal_value are internal functions for generic signal getter and setter, it is not recommended to use these two functions directly as they are too low level. You must follow the tutorial videos (hyperlinks on top right under "help" sub menu of c code editor) and use the correct methods for CAN signal manipulations.

If you still want to give it a try, follow the help doc. Do the following transformation:
"EngineData_2.EngSpeed" -> change to "EngSpeed_EngineData_2" -> fill into the first para.
![image](https://user-images.githubusercontent.com/16358754/143254709-47c6278a-bf30-40fb-b734-42b996fb84d2.png)

or you can click "tool" - "generate vc++ project" - open Database.c to see each signal definition clearly.
![image](https://user-images.githubusercontent.com/16358754/143255182-6f1503d6-eb9c-43f2-b8f5-03c10a405bdd.png)
