### ISSUE TITLE
Override automatic scaling of values on graph

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#28]
**Bug/feature request:** Add 'auto-scaling' button, which has the current behavior for graph scaling when a value is greater than the selected range. If not selected, keep the range fixed. Useful for when values have out of range errors

![image](https://user-images.githubusercontent.com/27743747/144528739-200df58d-5db8-4b9a-bc32-8c60c5100d63.png)

**Comment by freshhope** [comment]
now you can click the horz. or vert. button for auto adjustment
![image](https://user-images.githubusercontent.com/16358754/144729112-e2c9da71-8fe4-4c57-80ff-178cee9ba55b.png)
