### ISSUE TITLE
The service cannot be added to the combined service in the diagnostic panel

### ISSUE THREAD

**Issue by jianhun9527** [TOSUN-Shanghai/TSMaster#29]
![uTools_1638851545923](https://user-images.githubusercontent.com/55499877/144966855-b42c3617-4cd2-4a52-a539-a1e233bd713c.png)

**Comment by freshhope** [comment]
@XieYY135

**Comment by XieYY135** [comment]
Combined Service will be released in the new version.

**Comment by jianhun9527** [comment]
ok，thanks for your reply发自我的华为手机-------- 原始邮件 --------发件人： VehicleSW ***@***.***>日期： 2021年12月15日周三 11:15收件人： TOSUN-Shanghai/TSMaster ***@***.***>抄送： jianhun9527 ***@***.***>, Author ***@***.***>主    题： Re: [TOSUN-Shanghai/TSMaster] The service cannot be added to the combined service in the diagnostic panel (Issue #29)
Combined Service will be released in the new version.
