### ISSUE TITLE
Selecting CAN database twice

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#31]
**Bug:** When adding a message to the signal generator, sometimes if you select the DBC it'll scroll the view, but will require you to reselect the DBC a second time to correctly scroll to that message list.

![image](https://user-images.githubusercontent.com/27743747/145630300-f60d4778-9549-4395-841a-405f391063a5.png)

**Comment by freshhope** [comment]
Please upg. to latest beta version, this problem has been resolved.
