### ISSUE TITLE
Graphics cursor

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#33]
**Bug:** Cursor lines should move with the graphed data, not with the window

![image](https://user-images.githubusercontent.com/27743747/149051789-c244a621-a7e7-4f40-a3b8-d1aea65415cf.png)
![image](https://user-images.githubusercontent.com/27743747/149051813-996317ab-76ac-4853-8aab-d7c360e1d1ce.png)

**Comment by freshhope** [comment]
solved, please download latest beta version to check if problem still exists.
