### ISSUE TITLE
How do I add comment to a mini program library

### ISSUE THREAD

**Issue by vi-vian1** [TOSUN-Shanghai/TSMaster#37]
such as the following pic, i want to add comment,how can i do?
<img width="1209" alt="test" src="https://user-images.githubusercontent.com/92559552/159210305-f60fc185-947e-4af0-bc2b-22a357b93db7.png">

**Comment by freshhope** [comment]
![image](https://user-images.githubusercontent.com/16358754/159217899-54334cb1-2029-4912-a161-604e53f9acf6.png)
