### ISSUE TITLE
GCAN Support 

### ISSUE THREAD

**Issue by kobzar** [TOSUN-Shanghai/TSMaster#5]
Please, add support for GCAN devices like USBCAN-II C 
(https://aliexpress.ru/item/4001216169363.html?spm=a2g0o.store_pc_home.hotSpots_6000242637595.0)

**Comment by freshhope** [comment]
I know this kind of device coming from Guangcheng Tech. I'll add support if i get one in the future.

**Comment by alex-arc-boats** [comment]
@kobzar [this](https://www.aliexpress.com/item/1005001909644558.html?spm=a2g0o.productlist.0.0.6a236e0eXeMeYZ&algo_pvid=01857279-7963-4fc6-9fa2-7d04128a2e8d&algo_expid=01857279-7963-4fc6-9fa2-7d04128a2e8d-39&btsid=0bb0622e16190325787882656e7766&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) is the same as PCAN and works already

**Comment by pesky-cpu** [comment]
@kobzar [this](https://www.aliexpress.com/item/1005001909644558.html?spm=a2g0o.productlist.0.0.6a236e0eXeMeYZ&algo_pvid=01857279-7963-4fc6-9fa2-7d04128a2e8d&algo_expid=01857279-7963-4fc6-9fa2-7d04128a2e8d-39&btsid=0bb0622e16190325787882656e7766&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) is the same as PCAN and works with TSmaster already
