### ISSUE TITLE
TSMASTER sends flow control frame

### ISSUE THREAD

**Issue by jianhun9527** [TOSUN-Shanghai/TSMaster#58]
How can I configure the diagnostic panel to automatically send flow control frames under the UDS service

![image](https://user-images.githubusercontent.com/55499877/167594977-0388b940-d780-4a48-a704-a96a17912814.png)

22 The reason for the service failure is that the flow control frame is not sent to the lower computer

**Comment by dragoudin** [comment]
I confirm the issue. When I read a DID (22 XX XX service for example), if the expected response is big (more than 8 byte which requires multiple messages), only the first message is received in trace. TSMaster doesn't send the flow control frame.
I am wondering if the settings of tp can change anything?

**Comment by XieYY135** [comment]
In order to ensure timeliness, the transport layer is implemented in firmware. As follows:
![image](https://user-images.githubusercontent.com/12216193/169314139-ae2ff431-7bd4-4c03-a1b5-431c7e8924b5.png)

**Comment by dragoudin** [comment]
> In order to ensure timeliness, the transport layer is implemented in firmware. As follows: ![image](https://user-images.githubusercontent.com/12216193/169314139-ae2ff431-7bd4-4c03-a1b5-431c7e8924b5.png)

I use the latest version of TSMaster (2022.5.8.746) and it is not working on my side

**Comment by XieYY135** [comment]
> 

This function only supports specific hardware devices

**Comment by XieYY135** [comment]
> > In order to ensure timeliness, the transport layer is implemented in firmware. As follows: ![image](https://user-images.githubusercontent.com/12216193/169314139-ae2ff431-7bd4-4c03-a1b5-431c7e8924b5.png)
> 
> I use the latest version of TSMaster (2022.5.8.746) and it is not working on my side

This function only supports specific hardware devices

**Comment by totocaca123** [comment]
I use vector VN1630 hardware and it is not working.

**Comment by XieYY135** [comment]
> > > 
> > 
> > 
> > Hardware devices from TOSUN are required.
> 
> If this feature is not working with other hardware than TOSUN, it is an issue (it's not possible to send/receive UDS services bigger than 8 bytes). Send flow is a basic feature and if hardware is not compatible, I believe it can be done by software

In the current design, the diagnostic transport layer is implemented in the hardware.

**Comment by totocaca123** [comment]
> > > > 
> > > 
> > > 
> > > Hardware devices from TOSUN are required.
> > 
> > 
> > If this feature is not working with other hardware than TOSUN, it is an issue (it's not possible to send/receive UDS services bigger than 8 bytes). Send flow is a basic feature and if hardware is not compatible, I believe it can be done by software
> 
> In the current design, the diagnostic transport layer is implemented in the hardware.

I understand. It seems than Tosun hardware support natively flow control from hardware. 
But for people using different hardware (peak, vector...) this feature to test CanTp and diagnostic services is quiet important, and a such feature would be very interesting

**Comment by XieYY135** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Hardware devices from TOSUN are required.
> > > 
> > > 
> > > If this feature is not working with other hardware than TOSUN, it is an issue (it's not possible to send/receive UDS services bigger than 8 bytes). Send flow is a basic feature and if hardware is not compatible, I believe it can be done by software
> > 
> > 
> > In the current design, the diagnostic transport layer is implemented in the hardware.
> 
> I understand. It seems than Tosun hardware support natively flow control from hardware. But for people using different hardware (peak, vector...) this feature to test CanTp and diagnostic services is quiet important, and a such feature would be very interesting

After our test, we found that the timestamp of some hardware(of course not vector) is not so accurate, which is also the reason why we do not support it

**Comment by totocaca123** [comment]
> After our test, we found that the timestamp of some hardware(of course not vector) is not so accurate, which is also the reason why we do not support it

There might be some performance issue for the send flow (it is an hardware limitation). But if TsMaster doesn't support Send flow, it cause au problem for testing (most part of Diagnostic services UDS are not available without a tosun hardware).

**Comment by totocaca123** [comment]
A feature would be to enable a software send flow feature (if not supported by hardware)

**Comment by jianhun9527** [comment]
The flow control frame can be implemented through the C code editor, as follows, which has been verified
![image](https://user-images.githubusercontent.com/55499877/173225407-07f02565-57b2-4c72-8170-5e304b1cbf91.png)
