### ISSUE TITLE
Configure TX/RX direction in transmit_canfd_async

### ISSUE THREAD

**Issue by Matheus-Garbelini** [TOSUN-Shanghai/TSMaster#63]
Hello, I'm trying the example "Generic TCP UDP example".
I was able to communicate with TS master from a external UDP program, but the direction (**Dir**) of CAN FD frames is always TX:
![tx_direction](https://user-images.githubusercontent.com/6465668/169024182-d10a9419-034f-410d-a717-03c86007dc6f.png)

Is there a way to change the direction from TX to RX since I'm simulating CAN reception from an external program?

**Comment by freshhope** [comment]
![image](https://user-images.githubusercontent.com/16358754/177891025-5342ba1e-04e2-4e4c-b1b7-e8c163e65389.png)

Upg to the latest version, you are now able to inject any kind of message with inject api:


TCANFD c;

c.init_w_std_id(0x123, 8);
c.is_edl = false;
c.is_tx = false;

// to inject a CAN message into system
com.inject_can_message(&c);
// now this message is shown in CAN Trace...
