### ISSUE TITLE
Absolute Timestamp as unix timestamp?

### ISSUE THREAD

**Issue by Matheus-Garbelini** [TOSUN-Shanghai/TSMaster#64]
Hello, 

We are trying to save frames using absolute unix timestamp instead of relative, which starts from 0.
Is it possible to configure somewhere to absolute timestamp or change this after saving the file log via TSmaster SDK?

**Comment by XieYY135** [comment]
You can use the API to read the initial time of the record file, and add the relative time to get the absolute time

**Comment by Matheus-Garbelini** [comment]
@XieYY135 Thanks, can you point what is the function to get the initial time of the record file?
Is it specific to BLF format?

**Comment by Matheus-Garbelini** [comment]
Hi @XieYY135, any idea if we can use **FTimeUs** to inform our own hardware timestamp?

**Comment by Matheus-Garbelini** [comment]
@XieYY135 I'm using TSMaster GUI and miniprogram, not the standalone SDK API.
Yes, if I use the API to write a custom CAN Frame timestamp to `tslog_blf_write_canfd`, than it works.
This means that I cannot use the "Bus Logger" from TSMaster GUI. Is there atleast a system variable or miniprogram that can inform us what is the log file path the user specified in the "Bus Logger"?
This way the user doesn't need to manually modify the miniprogram code to change log file path.
![Screenshot_20220526_131237](https://user-images.githubusercontent.com/6465668/170420523-deaf2043-af82-4c57-976e-a27e44b0b0de.png)

**Comment by freshhope** [comment]
This system var will be available in the next release

**Comment by Matheus-Garbelini** [comment]
Thanks a lot @freshhope . Will close this issue. Will get back on my previous issue with more information which I think can be solved in the next release.

**Comment by Matheus-Garbelini** [comment]
Hi @freshhope, @XieYY135 
I'm trying to contact TSMaster to check for the possibility of a collaboration with our university for a CAN hardware that we are developing. Is there any email that I can reach for collaboration inquiries?
