### ISSUE TITLE
Support for Ethernet

### ISSUE THREAD

**Issue by hemalbavishi** [TOSUN-Shanghai/TSMaster#8]
Any plan to support Ethernet and SOME/IP?

**Comment by freshhope** [comment]
Of course, please wait

**Comment by Matheus-Garbelini** [comment]
Is there any update on this?
Im actually interested in using this software over a virtual CAN bus interface. Would be interesting if we can receive or transmit can frames via tcp, so we could use this software with whataver other hardware platforms are available.

Regards.

**Comment by freshhope** [comment]
TCP and UDP are already implemented in mini program API, you can see the demo here 
![image](https://user-images.githubusercontent.com/16358754/160508021-564ac0f1-2f64-45fa-a2c3-1d93c7b0619c.png)

we are still working hard on SOME/IP

**Comment by Matheus-Garbelini** [comment]
@freshhope got it thanks.
