### ISSUE TITLE
[System Variables] Add new data types 

### ISSUE THREAD

**Issue by totocaca123** [TOSUN-Shanghai/TSMaster#81]
Currently some data types are missing (boolean, uint8, sint8, uint16...).
![image](https://user-images.githubusercontent.com/42418580/200695849-060ed673-7015-414b-8012-5849aee54d84.png)

Missing data type enum

**Comment by freshhope** [comment]
This is because you can always use Int32 to replace sint8, boolean, and UInt32 to replace uint8 and uint16.
The reason why we do not include boolean and sint8 is to simply. System variable's main focus is functionality.

**Comment by totocaca123** [comment]
OK it seems logical (so I oversize my data and cast in script)
